services:
  frontend:
    container_name: frontend
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: always
    command: pnpm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000