services:
  frontend:
    container_name: frontend
    build:
      context: .
      # target: prod
      # dockerfile: Dockerfile
    restart: always
    # command: pnpm run start
    environment:
      - NODE_ENV=production
    # volumes:
    #   - /app/node_modules
    #   - /app/.next
    ports:
      - 3000:3000